# Generated by Django 4.2.7 on 2023-11-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_ingreso',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingreso_producto.proveedor')),
            ],
            options={
                'db_table': 'planta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField()),
                ('ticket', models.CharField(max_length=255)),
                ('tanque_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('conductor', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_tracto', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_cisterna', models.CharField(blank=True, max_length=255, null=True)),
                ('guia_remision', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_guia', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_bruto', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_tara', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingreso_producto.planta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingreso_producto.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingreso_producto.proveedor')),
                ('tipo_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingreso_producto.tipoingreso')),
            ],
            options={
                'db_table': 'ingreso_producto',
                'ordering': ['-id'],
            },
        ),
    ]
