# Generated by Django 4.2.7 on 2023-11-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField()),
                ('ticket', models.CharField(max_length=255)),
                ('tanque_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('conductor', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_tracto', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_cisterna', models.CharField(blank=True, max_length=255, null=True)),
                ('guia_remision', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_guia', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_bruto', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_tara', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_neto', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('peso_neto_disponible', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ingreso_producto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_ingreso',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_muestra',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_tanque',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('capacidad_disponible', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('tipo_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.tipotanque')),
            ],
            options={
                'db_table': 'tanque',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.proveedor')),
            ],
            options={
                'db_table': 'planta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoProductoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha', models.DateField()),
                ('ingreso_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.ingresoproducto')),
                ('tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.tanque')),
            ],
            options={
                'db_table': 'ingreso_producto_tanque',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.planta'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.producto'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.proveedor'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='tipo_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.tipoingreso'),
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_muestreador', models.CharField(blank=True, max_length=255, null=True)),
                ('acidez', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('humedad', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('impureza', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('estearina', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('anisidina', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('linoleico', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('epa', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('dha', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('indice_yodo', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('ingreso_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.ingresoproducto')),
                ('tipo_muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.tipomuestra')),
            ],
            options={
                'db_table': 'calidad',
                'ordering': ['-id'],
            },
        ),
    ]
