# Generated by Django 4.2.7 on 2023-11-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIngresoProductoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha', models.DateField()),
                ('ingreso_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.ingresoproducto')),
                ('ingreso_producto_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.ingresoproductotanque')),
                ('tanque_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historialingresoproductotanque_destino', to='operacional.tanque')),
                ('tanque_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historialingresoproductotanque_origen', to='operacional.tanque')),
            ],
            options={
                'db_table': 'historial_ingreso_producto_tanque',
                'ordering': ['-id'],
            },
        ),
    ]
