# Generated by Django 4.2.7 on 2023-11-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_tanque',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('tipo_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanque.tipotanque')),
            ],
            options={
                'db_table': 'tanque',
                'ordering': ['-id'],
            },
        ),
    ]
